### PR TITLE
Fix User Guide: Specify full name 

### LINKED ISSUE #192: [PE-D][Tester B] User Guide not exactly accurate
User guide did not specify full name for the feature “task todo”. Can be confusing when 
user tries to use only the given name.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: dr-arrgghh/ped#2

### PR DESCRIPTION
**Pull request by bananamonkey4655**
Fixes #192

### CODE REVIEW

**Review by dexter-sim — APPROVED** [review]
lgtm

**Review by dexter-sim — CHANGES_REQUESTED** [review]
You may have forgotten to update the names to `Alex Yeoh` and `Bernice Yu` in examples for Adding Event and Adding Deadline.

**Comment by bananamonkey4655** [comment]
good catch, fixed @dexter-sim

**Review by dexter-sim — APPROVED** [review]
lgtm

**Pull request merged**
